#!/bin/bash

# To update the version shipped in this quickstart, bump this variable:
install_version="8.0.2"
download_url=http://download.owncloud.org/community/owncloud-${install_version}.tar.bz2
download_md5=http://download.owncloud.org/community/owncloud-${install_version}.tar.bz2.md5

echo "Starting build..."

# Download and install dir
install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${install_version}

# Used in this script only
current_version_dir=${OPENSHIFT_DATA_DIR}current

# If already installed in the current gear, there is nothing to do
[ -d "${current_version_dir}" ] && exit 0

echo "ownCloud not yet installed..."

# Get it
mkdir -p $install_dir

pushd ${install_dir} >/dev/null
echo "Downloading ${download_url}..."
curl -s ${download_url} > owncloud-${install_version}.tar.bz2

# Verify
echo "Verifying md5..."
tar_md5=$(md5sum owncloud-${install_version}.tar.bz2 | cut -d ' ' -f 1)
url_md5=$(curl -s ${download_md5} | cut -d ' ' -f 1)
if [ "${tar_md5}" != "${url_md5}" ]; then
  echo "ERROR: ownCloud ${install_version} MD5 checksum mismatch."
  exit 1;
fi

# Install
echo "Extracting owncloud-${install_version}.tar.bz2..."
tar --strip-components=1 -jxf owncloud-${install_version}.tar.bz2
rm -rf owncloud-${install_version}.tar.bz2

echo "Setting current version to ${install_version}..."
echo $install_version > ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version

popd >/dev/null

echo "Completed build."
