#!/bin/bash

dest_dir=${OPENSHIFT_DATA_DIR}current
current_version=$(cat ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version)
build_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${current_version}

echo "Starting deploy..."

if [ ! -d "${dest_dir}" ]; then
  echo "Copying to ${dest_dir}..."
  mkdir -p $dest_dir
  cp -rf ${build_dir}/* ${dest_dir}/
fi

# Replace the php/ directory with provided installation
if [ -d ${OPENSHIFT_REPO_DIR}php ]; then
  echo "Linking the instalation with the repo dir..."
  if [ -f $OPENSHIFT_REPO_DIR/php/config/autoconfig.php ]
  then
    cp $OPENSHIFT_REPO_DIR/php/config/autoconfig.php $dest_dir/config
  fi
  rm -rf ${OPENSHIFT_REPO_DIR}php
fi
ln -sf ${dest_dir} ${OPENSHIFT_REPO_DIR}php

set -e

echo "Checking MySQL database..."

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.5" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then 
   exit 5
fi

echo "Completed deploy."
