#!/bin/bash
# This is a simple post deploy hook executed after your application 
# is deployed and started.  This script gets executed directly, so 
# it could be python, php, ruby, etc.

source $OPENSHIFT_CARTRIDGE_SDK_BASH

echo "Starting post_deploy..."

# Need to GET the main page to trigger the autoconfig of the ownCloud instance
if [ -f $OPENSHIFT_REPO_DIR/php/config/autoconfig.php ]
then
  # Set the initial password
  admin_password=$(generate_password)

  # save password to file so we can read it from autoconfig.php
  echo $admin_password > $OPENSHIFT_DATA_DIR/.initial_owncloud_password

  echo "Requesting index.php to trigger autoconfig..."
  curl -s http://${OPENSHIFT_APP_DNS}/index.php

  client_result ""
  client_result "ownCloud configured successfully."
  client_result "Take note of the default admin credentials:"
  client_result ""
  client_result "      Username: admin"
  client_result "      Password: $admin_password"
  client_result ""
  client_result "Don't forget to change your admin password!"
  client_result ""

fi

# Copy config to persisted data directory
pushd $OPENSHIFT_REPO_DIR/php
if [ ! -f $OPENSHIFT_DATA_DIR/${OPENSHIFT_APP_NAME}-config.php ]
then
  echo "Persisting configuration..."
  mv config/config.php ${OPENSHIFT_DATA_DIR}/${OPENSHIFT_APP_NAME}-config.php
  ln -s $OPENSHIFT_DATA_DIR/$OPENSHIFT_APP_NAME-config.php $OPENSHIFT_REPO_DIR/php/config/config.php
fi
popd

echo "Completed post_deploy."
