#!/bin/bash

echo "Starting pre_build..."

config_file=$OPENSHIFT_DATA_DIR${OPENSHIFT_APP_NAME}-config.php

# Confirm configuration exists, if so restore it
if [ -f $config_file ]
then
    echo "Configuration exists, creating link..."
    ln -s $config_file ${OPENSHIFT_REPO_DIR}php/config/config.php

    # Remove autoconfig it doesn't get overwritten
    if [[ -f ${OPENSHIFT_REPO_DIR}php/config/autoconfig.php ]] ; then 
        rm ${OPENSHIFT_REPO_DIR}php/config/autoconfig.php
    fi
fi

echo "Completed pre_build."

